<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace Proto;

use Google\Protobuf\Internal\DescriptorPool;
use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

class Friend extends \Google\Protobuf\Internal\Message
{
    private $name = '';

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

}

class Person extends \Google\Protobuf\Internal\Message
{
    private $name = '';
    private $id = 0;
    private $email = '';
    private $friend = null;

    public function getName()
    {
        return $this->name;
    }

    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    public function getFriend()
    {
        return $this->friend;
    }

    public function setFriend(&$var)
    {
        GPBUtil::checkMessage($var, \Proto\Friend::class);
        $this->friend = $var;
    }

}

$pool = DescriptorPool::getGeneratedPool();

$pool->internalAddGeneratedFile(hex2bin(
    "0a87010a0c706572736f6e2e70726f746f120550726f746f22160a064672" .
    "69656e64120c0a046e616d6518012001280922500a06506572736f6e120c" .
    "0a046e616d65180120012809120a0a026964180220012805120d0a05656d" .
    "61696c180320012809121d0a06667269656e6418042001280b320d2e5072" .
    "6f746f2e467269656e64620670726f746f33"
));

